- name: Include install nftables task
  include_tasks: install_nftables_arch.yml
  when: ansible_facts.distribution == 'Archlinux'

- name: Include install nftables task
  include_tasks: install_nftables_ubuntu.yml
  when: ansible_facts.distribution == 'Ubuntu'

- name: Creates nftables directory
  file:
    path: /etc/nftables/
    state: directory
    mode: 0600

- name: Copy basic nftables rules
  copy:
    src: nftables.conf
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: 0600
  notify: Restart nftables
