- name: Install nftables
  package:
    name:
      - nftables
    state: present

- name: Creates nftables directory
  file:
    path: /etc/nftables/
    state: directory
    mode: '0700'

- name: Creates input directory
  file:
    path: /etc/nftables/input
    state: directory
    mode: '0700'

- name: Creates forward directory
  file:
    path: /etc/nftables/forward
    state: directory
    mode: '0700'

- name: Creates other directory
  file:
    path: /etc/nftables/other
    state: directory
    mode: '0700'

- name: Copy basic nftables rules
  copy:
    src: nftables.conf
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0600'
  notify: Restart nftables
