- name: Install nftables
  package:
    name:
      - nftables
    state: present

- name: Creates nftables directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  with_items:
    - /etc/nftables/
    - /etc/nftables/input
    - /etc/nftables/forward
    - /etc/nftables/other

- name: Copy basic nftables rules
  copy:
    src: nftables.conf
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0600'
  notify: Restart nftables
