- name: Continue only on ubuntu or debian
  assert:
    that:
      - "ansible_facts.os_family == 'Debian'"

- name: Assert bind_address is IP address
  assert:
    that:
      - "mariadb_bind_address | ansible.netcommon.ipaddr"
