- name: "Fix php versions bug"
  block:
    - name: Symlink centreon php config
      ansible.builtin.file:
        src: /etc/php/8.0/mods-available/centreon.ini
        dest: /etc/php/8.1/mods-available/centreon.ini
        owner: root
        group: root
        state: link
      notify: Restart centreon php

    - name: Enable centreon config in fpm
      ansible.builtin.file:
        src: /etc/php/8.0/mods-available/centreon.ini
        dest: /etc/php/8.1/fpm/conf.d/50-centreon.ini
        owner: root
        group: root
        state: link
      notify: Restart centreon php

    - name: Enable centreon config in cli
      ansible.builtin.file:
        src: /etc/php/8.0/mods-available/centreon.ini
        dest: /etc/php/8.1/cli/conf.d/50-centreon.ini
        owner: root
        group: root
        state: link
      notify: Restart centreon php

    - name: Sylink pool config
      ansible.builtin.file:
        src: /etc/php/8.0/fpm/pool.d/centreon.conf
        dest: /etc/php/8.1/fpm/pool.d/centreon.conf
        owner: root
        group: root
        state: link
      notify: Restart centreon php

- name: Fix centreon permissions
  block:
    - name: Fix engine permissions
      ansible.builtin.file:
        path: /etc/centreon-engine/
        owner: www-data
        group: centreon-engine
        recurse: true

    - name: Fix broker permissions
      ansible.builtin.file:
        path: /etc/centreon-broker/
        owner: www-data
        group: centreon-broker
        recurse: true
