- name: Include extended validation
  include_tasks: argument_validation.yml
  when: extended_validation is defined

- name: Include extended validation
  include_tasks: setup_centreon_repo.yml

- name: Install centreon-central
  apt:
    pkg:
      - centreon-central
    state: present

- name: Install nagios plugins
  apt:
    pkg:
      - nagios-nrpe-plugin
      - monitoring-plugins
    state: present

- name: Install backup script dependencies
  apt:
    pkg:
      - mariadb-client
      - bc
    state: present

- name: Set php timezone
  ansible.builtin.lineinfile:
    path: "/etc/php/{{ centreon_php_version }}/mods-available/centreon.ini"
    regexp: '^date.timezone '
    line: "date.timezone = {{ centreon_timezone }}"
  notify: Restart centreon php

- name: Include version specific fix
  include_tasks: "fix-{{ centreon_version }}.yml"
  when: centreon_enable_fix

- name: Start and enable centreon services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    masked: false
  with_items:
    - "php{{ centreon_php_version }}-fpm"
    - apache2
    - centreon
    - cbd
    - centengine
    - gorgoned
    - snmptrapd
    - centreontrapd
    - snmpd
