- name: Install centreon dependencies
  apt:
    pkg:
      - lsb-release
      - ca-certificates
      - apt-transport-https
      - software-properties-common
      - wget
      - gnupg2
    state: present

- name: Create /etc/apt/keyrings/ directory
  file:
    path: /etc/apt/keyrings/
    state: directory
    owner: "root"
    group: "root"
    mode: '0755'

- name: Get centreon repo key
  ansible.builtin.get_url:
    url: 'https://apt-key.centreon.com'
    dest: /etc/apt/keyrings/centreon.asc
    mode: '0644'

- name: Create centreon repo file
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/centreon.asc] https://apt.centreon.com/repository/{{ centreon_version }}/ {{ ansible_distribution_release }} main"
    state: present
