- name: Install hd-idle
  package:
    name:
      - hd-idle
    state: present

- name: Template hd-ide config
  template:
    src: config.j2
    dest: /etc/default/hd-idle
    owner: root
    group: root
    mode: '0644'
  notify: Restart hd-idle

- name: Start hd-idle
  systemd:
    name: hd-idle
    state: started
    enabled: true
    masked: false
