- name: Install unattended-upgrades
  apt:
    pkg:
      - unattended-upgrades
    state: present

- name: Copy unattended-upgrades configuration
  copy:
    src: '20auto-upgrades'
    dest: '/etc/apt/apt.conf.d/20auto-upgrades'
    owner: root
    group: root
    mode: "600"
