argument_specs:
  main:
    short_description: Parameters for grafana role
    options:
      grafana_service_name:
        type: "str"
        required: true
        description: "Name for grafana systemd unit"
      grafana_config_path:
        type: "str"
        required: true
        description: "Path to grafana config"
      grafana_data_path:
        type: "str"
        required: false
        default: "/var/lib/grafana/"
        description: "Path to grafana storage"
      grafana_logs_path:
        type: "str"
        required: false
        default: "/var/log/grafana/"
        description: "Path to grafana logs"
      grafana_protocol:
        type: "str"
        required: false
        choices:
          - 'http'
          - 'https'
        default: 'http'
        description: "Which protocol to use"
      grafana_bind_ip:
        type: "str"
        required: false
        default: '127.0.0.1'
        description: "On which IP listen"
      grafana_http_port:
        type: "str"
        required: false
        default: '3000'
        description: "On which port listen"
      grafana_user:
        type: "str"
        required: false
        default: 'grafana'
        description: "Which user use"
