- name: Remove sysstat cron
  ansible.builtin.file:
    state: absent
    path: "/etc/cron.d/sysstat"

- name: Disable ubuntu advantage
  systemd:
    name: ua-timer.timer
    state: stopped
    enabled: false
    masked: true

- name: Disable packagekit
  systemd:
    name: packagekit.service
    state: stopped
    enabled: false
    masked: true
