- name: Install packages for raspberry
  apt:
    pkg:
      - libraspberrypi-bin
    state: present

- name: Remove snapd
  apt:
    pkg:
      - snapd
    state: absent

- name: Remove multipathd
  apt:
    pkg:
      - multipath-tools
    state: absent
