- name: Restart zrepl on backup
  systemd:
    name: "zrepl-{{ zrepl_source_server }}.service"
    state: restarted

- name: Restart zrepl proxy on backup
  systemd:
    name: "zrepl-{{ zrepl_source_server }}-proxy.service"
    state: restarted

- name: Restart zrepl socket on backup
  systemd:
    name: "zrepl-{{ zrepl_source_server }}.socket"
    state: restarted
