- name: Install wireguard
  apt:
    pkg: wireguard-tools
    state: present
  when: ansible_facts.os_family == 'Debian'

- name: Install wireguard
  pacman:
    name: wireguard-tools
    state: present
  when: ansible_facts.os_family == 'Archlinux'
