- name: Generate transfer binary # noqa no-changed-when
  ansible.builtin.command: /usr/bin/go build -o ../bin/transfersh main.go
  become: true
  become_user: "{{ transfer_user }}"
  args:
    chdir: "{{ transfer_path }}/git"

- name: Restart transfer
  systemd:
    name: transfer
    state: restarted
    enabled: true
