- name: Include extended validation
  include_tasks: argument_validation.yml
  when: extended_validation is defined

- name: Dehydrated block
  when: nginx_create_vhost_use_dehydrated
  block:
    - name: Add domain to domains.txt
      ansible.builtin.lineinfile:
        path: /etc/dehydrated/domains.txt
        state: present
        regexp: '^{% for domain in nginx_create_vhost_domain %}{{ domain }} {% endfor %}'
        line: '{% for domain in nginx_create_vhost_domain %}{{ domain }} {% endfor %}'
        create: true
        owner: "{{ dehydrated_user }}"
        group: "{{ dehydrated_user }}"
        mode: "644"
      notify: Generate certificates

    - name: Generate certificate before nginx reload
      meta: flush_handlers

- name: "Create {{ nginx_create_vhost_domain[0] }}"
  template:
    src: "vhost_common.j2"
    dest: "/etc/nginx/sites-avaliable/{{ nginx_create_vhost_domain[0] }}.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: '0644'
  notify: Reload nginx

- name: Create {{ nginx_create_vhost_domain[0] }} directory
  file:
    path: '{{ nginx_create_vhost_root }}'
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: '0755'
  when: nginx_create_vhost_type == "domain"

- name: Enable http conf
  ansible.builtin.file:
    src: "/etc/nginx/sites-avaliable/{{ nginx_create_vhost_domain[0] }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ nginx_create_vhost_domain[0] }}.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    state: link
  notify: Reload nginx
