- name: "Install base packages for {{ ansible_facts.distribution }}"
  apt:
    pkg:
      - nano
      - sudo
      - git
      - vim
      - net-tools
      - python3
      - htop
      - iotop
      - sysstat
      - tcpdump
      - man
      - gdu
      - lsof
      - screen
      - tmux
      - gpg
      - curl
      - zstd
      - telnet
      - mtr
    state: present
