- name: Install base packages for arch
  pacman:
    name:
      - base
      - base-devel
      - sudo
      - nano
      - git
      - vim
      - net-tools
      - python
      - htop
      - iotop
      - zsh
      - sysstat
      - tcpdump
      - man
      - gdu
      - lsof
      - screen
      - tmux
      - zstd
      - grc
      - pacman-contrib
      - inetutils
      - mtr
      - bat
    state: present
