- name: Assert prometheus listen port number is in range of unix ports
  assert:
    that:
      - prometheus_listen_port is defined
      - prometheus_listen_port > 0
      - prometheus_listen_port < 65535

- name: Assert prometheus_listen_address is IP address
  assert:
    that:
      - "prometheus_listen_address | ansible.netcommon.ipaddr"
