- name: Include extended validation
  include_tasks: argument_validation.yml
  when: extended_validation is defined

- name: Install postfix
  package:
    name:
      - postfix
    state: present

- name: Create conf.d directory
  ansible.builtin.file:
    path: "/etc/postfix/conf.d"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy common postfix configuration
  template:
    src: common.cf.j2
    dest: /etc/postfix/conf.d/01-common.cf
    mode: '0644'
    owner: root
    group: root

- name: Copy relayhost configuration
  template:
    src: relayhost.cf.j2
    dest: /etc/postfix/conf.d/60-relayhost.cf
    mode: '0644'
    owner: root
    group: root
  when: postfix_relayhost is defined

- name: Copy TLS configuration
  template:
    src: tls.cf.j2
    dest: /etc/postfix/conf.d/20-tls.cf
    mode: '0644'
    owner: root
    group: root
  when: postfix_enable_tls

- name: Remove unneeded headers
  when: postfix_remove_headers
  block:
    - name: Copy postfix headers configuration
      template:
        src: remove_headers.cf.j2
        dest: /etc/postfix/conf.d/30-remove_headers.cf
        mode: '0644'
        owner: root
        group: root

    - name: Copy headers list
      template:
        src: smtp_header_checks.j2
        dest: /etc/postfix/smtp_header_checks
        mode: '0644'
        owner: root
        group: root

- name: Assemble from fragments
  import_tasks:
    file: assemble.yml

- name: Start and enable postfix
  systemd:
    name: postfix
    state: started
    enabled: true
    masked: false
